name: Release Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [closed]

jobs:
  release_web:
    name: cppandaction release
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Create Build Directory
        run: cmake -E make_directory ${{github.workspace}}/build

      - name: Configure CMake
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release

      - name: Build

        run: cmake --build ./build --config Release

- name: Create Artifact
  run: |
    mkdir release
    cp build/main release/main
    
- name: Publish Artifact
  uses: actions/upload-artifact@v2
  with:
    name: cppandaction release
    path: release